apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ms-inventario-external-secret
  namespace: ms-inventory
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ms-inventario-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/ms-inventario/config
        property: DB_PASSWORD
    - secretKey: PRODUCTOS_API_KEY
      remoteRef:
        key: prod/ms-inventario/config
        property: PRODUCTOS_API_KEY
    - secretKey: SERVICE_API_KEY
      remoteRef:
        key: prod/ms-inventario/config
        property: SERVICE_API_KEY
    - secretKey: DB_HOST
      remoteRef:
        key: prod/ms-inventario/config
        property: DB_HOST
    - secretKey: KAFKA_BOOTSTRAP_SERVERS
      remoteRef:
        key: prod/ms-inventario/config
        property: KAFKA_BOOTSTRAP_SERVERS
